### ISSUE TITLE
Broken syntax highlight in typecasts

### ISSUE THREAD

**Issue by alem0lars** [HerringtonDarkholme/yats.vim#45]
See line 77 of picture below:

![2018-02-26-103240_964x972_scrot](https://user-images.githubusercontent.com/336957/36663035-917ac436-1ae0-11e8-9333-88cd93c3783f.png)

**Comment by HerringtonDarkholme** [comment]
The problem is you cannot write function type in arrow function.

I cannot support this. This is Vim's syntax highlighting limitation. 

Again, your arrow function is contextually typed.
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/passport-facebook/index.d.ts#L44-L45

Manual annotation doesn't give any extra type safety.
