### ISSUE TITLE
Can't change color of typescriptProp

### ISSUE THREAD

**Issue by sidorenkobw** [HerringtonDarkholme/yats.vim#46]
Hi, I add the following line to my color scheme in it doesn't change the color of method calls:
hi typescriptProp gui=NONE guifg=#e8d07a guibg=NONE
Thanks

**Comment by HerringtonDarkholme** [comment]
Hi

typescriptProp is a special group. It is labeled as `transparent` so your color scheme won't take effect.

**Comment by sidorenkobw** [comment]
Thanks but I tried:
hi link typescriptProp Function
and the color of method call is still the same. How can change method call color?

**Comment by HerringtonDarkholme** [comment]
You cannot. 

> There is no distinction between method and property in yats.

**Comment by sidorenkobw** [comment]
Can I request this functionality? You made an awesome and detailed syntax highlight but I can't change such a simple thing: nor method call color nor property access color.

**Comment by HerringtonDarkholme** [comment]
I cannot because it introduces performance overhead. I used to include it but removed it after performance profiling. 

I recommend you clone this project and change these lines https://github.com/HerringtonDarkholme/yats.vim/blob/06e271c75478f5e793ce1e6285da1c6ca70de067/syntax/basic/identifiers.vim#L14-L18
