### ISSUE TITLE
`return` wrongfully reported as error

### ISSUE THREAD

**Issue by afontaine** [HerringtonDarkholme/yats.vim#5]
![2016-02-26 14_41_26-amounts component ts c__work_mmxpr_slag_webapp_app_ts_remoteteller_components](https://cloud.githubusercontent.com/assets/3373136/13363410/2f527206-dc97-11e5-848c-442b869f3c77.png)

Thank you for looking at all these issues. :smiley:

**Comment by HerringtonDarkholme** [comment]
Thanks for your report.
But I don't think this is fixable.
Arrow function and parenthesis expression have the same priority. Vim cannot distinguish them because it cannot lookahead or backtracking. 
Consider this:
```typescript
function a() {
  return (a, a)
}

function b() {
  return (a, a) => 123
}
```
Vim can only see the start `(` , from which Vim cannot tell if it is arrow function or parenthesis.

**Comment by HerringtonDarkholme** [comment]
If you write arrow function argument in the same line, then it will be solved.

**Comment by afontaine** [comment]
That's too bad, typescript lines get pretty long with type annotations. Wouldn't the `) => {` be enough to declare it a function block? I can't think of any code snippets where the above isn't an arrow function.

**Comment by HerringtonDarkholme** [comment]
`) => {` only works on few situations. Expressions like `(): (i: number) => string => (i) => '123'` will fail any way

**Comment by HerringtonDarkholme** [comment]
In practice I don't find it is a problem. If you use an arrow function, you usually use it as a callback. It is usually contextually typed, so no annotation is needed, so line length budget is not that tight.

**Comment by dawnofthedev** [comment]
I'm seeing return (and const+let) flagged as red error in a lot of my code. This plugin is not usable because it's so distracting. 

I'm not exactly sure what's common practice in syntax plugins but I would suggest you disable error flagging especially considering a) it's incorrect b) almost everyone uses ale or syntastic etc.

**Comment by alem0lars** [comment]
@HerringtonDarkholme Any progress on the issue?

**Comment by alem0lars** [comment]
It is broken only in multi-line (in my tests)

**Comment by HerringtonDarkholme** [comment]
@alem0lars The statement I present above is a valid javascript statement, it evaluates to either the variable `s` wrapped in parenthesis, or an arrow function that takes a parameter named `string` and returns an empty string.

It is ambiguous in TypeScript, though. Actually, TypeScript and probably its user think it is incomplete statement that evaluates to a partial ternary of which the true path is arrow function.

**Comment by HerringtonDarkholme** [comment]
I gave it a partial fix: now arrow function argument can span multiple lines. But only if arguments themselves don't contain parenthesis. If they do contain and break syntax highlight, it is usually caused by annotating callback type. Please consider changing code to get cleaner source.
